In [1]:
import numpy as np

In [2]:
num_users = 10 
num_movies = 5 
ratings_data = np.random.randint(0, 2, size=(num_users, num_movies)) 
print(ratings_data.shape) 
print(ratings_data) 

(10, 5)
[[1 0 0 0 0]
 [0 1 1 1 1]
 [0 0 1 0 1]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [1 0 1 0 0]
 [0 0 0 1 0]
 [1 1 0 1 0]
 [0 1 1 1 1]
 [1 0 0 0 0]]


In [3]:
def sigmoid(x): 
    return 1 / (1 + np.exp(-x)) 

In [4]:
num_hidden_units = 3 
weights = np.random.normal(0, 0.1, (num_movies, num_hidden_units)) 
print(weights.shape) 
print(weights) 

(5, 3)
[[-0.24921593 -0.00291876  0.1009504 ]
 [ 0.00712028 -0.08936638 -0.09502038]
 [ 0.07535017 -0.06761315  0.01220504]
 [ 0.08743992  0.01413193 -0.03282228]
 [-0.07725052 -0.08562806  0.04644373]]


In [5]:
visible_bias = np.zeros(num_movies) 
print(visible_bias.shape) 
hidden_bias = np.zeros(num_hidden_units) 
print(hidden_bias.shape) 
learning_rate = 0.1 

(5,)
(3,)


In [7]:
num_epochs = 1000 
for epoch in range(num_epochs): 
    for user_ratings in ratings_data:
        hidden_probabilities = sigmoid(np.dot(user_ratings, weights) + hidden_bias)
        positive_associations = np.outer(user_ratings, hidden_probabilities)

In [9]:
visible_probabilities = sigmoid(np.dot(hidden_probabilities, weights.T) +visible_bias)
hidden_probabilities_recon = sigmoid(np.dot(visible_probabilities, weights) +hidden_bias)
negative_associations = np.outer(visible_probabilities, hidden_probabilities_recon)      

In [10]:
weights += learning_rate * (positive_associations - negative_associations)         
visible_bias += learning_rate * (user_ratings - visible_probabilities)         
hidden_bias += learning_rate * (hidden_probabilities - hidden_probabilities_recon) 

In [12]:
user_id = 5 
user_ratings = ratings_data[user_id] 
print(user_ratings) 
hidden_probabilities = sigmoid(np.dot(user_ratings, weights) + hidden_bias) 
visible_probabilities = sigmoid(np.dot(hidden_probabilities, weights.T) + visible_bias) 
predicted_ratings = visible_probabilities 
print("Predicted ratings for user", user_id, ":", predicted_ratings) 

[1 0 1 0 0]
Predicted ratings for user 5 : [0.50684418 0.45707757 0.48052218 0.4855785  0.46619234]
